### ISSUE TITLE
lsb-compat Debian 9 stretch

### ISSUE THREAD

**Issue by knotheu** [dewhisna/KingJamesPureBibleSearch#4]
Debian 9 will not install lsb (sudo apt install lsb) instead I get this message,
"Note, selecting 'lsb-compat' instead of 'lsb'
lsb-compat is already the newest version (9.20161125)".

What to do to install purebiblesearch if I cannot install lsb? I know to use the webchannel purebiblesearch, but.

**Comment by dewhisna** [comment]
Have you actually tried running the King James Pure Bible Search (KJPBS) installer yet??  If not, please try running it.  According to package details searchable online, `lsb-compat` provides `lsb` and `lsb-core` (in other words, it replaces them as the package that should be installed instead):  https://debian.pkgs.org/9/debian-main-amd64/lsb-compat_9.20161125_amd64.deb.html ... `lsb` itself is just a meta-package that brings in the various components of Linux Standard Base.  It looks like on Debian Stretch they've reorganized the packages so that it's provided by `lsb-compat` now.

KJPBS mainly needs `lsb-core` (which `lsb-compat` provides) and `alien`.  Most likely, you already have `alien` installed as well, as it's a requirement for LSB compatibility.  But if not, you can try `sudo apt-get install alien` to make sure.  But I believe you should be able to run KJPBS just fine.  If not, let me know and I'll reopen this ticket and examine it in more detail.

**Comment by knotheu** [comment]
Yes I tried to run the installer that is when the message comes up saying I need to install lsb. I looked for lsb in the package manager but all there is lsb-compat. Yes I did try to install lsb from the command line (sudo apt install lsb) and I get the message lsb-compat is the current package.Dave
    On Saturday, June 30, 2018, 10:15:18 PM PDT, Donna Whisnant <notifications@github.com> wrote:  
 
 
Have you actually tried running the King James Pure Bible Search (KJPBS) installer yet?? If not, please try running it. According to package details searchable online, lsb-compat provides lsb and lsb-core (in other words, it replaces them as the package that should be installed instead): https://debian.pkgs.org/9/debian-main-amd64/lsb-compat_9.20161125_amd64.deb.html ... lsb itself is just a meta-package that brings in the various components of Linux Standard Base. It looks like on Debian Stretch they've reorganized the packages so that it's provided by lsb-compat now.

KJPBS mainly needs lsb-core (which lsb-compat provides) and alien. Most likely, you already have alien installed as well, as it's a requirement for LSB compatibility. But if not, you can try sudo apt-get install alien to make sure. But I believe you should be able to run KJPBS just fine. If not, let me know and I'll reopen this ticket and examine it in more detail.

**Comment by knotheu** [comment]
I'll check it out and get back to you if it works. I didn't see lsb-release in the Synaptic Package Manager when I did a search for lsb.
    On Sunday, July 1, 2018, 7:23:13 AM PDT, Donna Whisnant <notifications@github.com> wrote:  
 
 
The KJPBS installer calls the lsb_release program, which is usually installed with the main lsb package. The installer uses that utility to determine the version of LSB installed. According to the Debian package list (https://packages.debian.org/stretch/lsb-release), they have that utility in a separate package called lsb-release, which apparently isn't sourced as a dependency. Try running the following:
sudo apt-get update
sudo apt-get install lsb-release

Then try the KJPBS installer again after you install that package.

**Comment by knotheu** [comment]
yes that was the problem, after installing lsb, lsb-release, tried to install KJPB got the message "However, the alien package (which is necessary to install LSB packages on Debian-based systems) is currently not installed."sudo apt install alienran the KJPB installer again and worked perfectly. This operating system is Debian 9 Stretch, seems alien does not come installed.Thank you for the help,Dave
    On Sunday, July 1, 2018, 7:23:13 AM PDT, Donna Whisnant <notifications@github.com> wrote:  
 
 
The KJPBS installer calls the lsb_release program, which is usually installed with the main lsb package. The installer uses that utility to determine the version of LSB installed. According to the Debian package list (https://packages.debian.org/stretch/lsb-release), they have that utility in a separate package called lsb-release, which apparently isn't sourced as a dependency. Try running the following:
sudo apt-get update
sudo apt-get install lsb-release

Then try the KJPBS installer again after you install that package.

**Comment by dewhisna** [comment]
Glad you got it working.  And yes, as I mentioned earlier in this thread, `alien` is required.  That's the program that converts RPM packages to DEB packages.  Debian is sort of weird with the whole LSB concept.  While Debian itself is probably one of the most LSB compliant distros, due to their strict requirements they actually don't claim to be LSB compliant.

Normally, just installing `lsb` on most distros gets you all of the core pieces you need, like `lsb-core`, `lsb-release`, and `alien`, etc.  That used to be the case with Debian.  But it seems that since they don't consider themselves "LSB compliant", they've split up the LSB packages -- unfortunately that makes it more difficult for the average user to get things installed.

Thanks for working through this and letting me know about it.  I will see about updating the text on my http://www.purebiblesearch.com/ website to include some details about this to help others out.

If you are wondering why KJPBS uses LSB in the first place, it's so that I can have two installers (one 32-bit and one 64-bit) that will work on nearly all distributions of Linux.  Otherwise, I'd have to develop and maintain system packages for every Linux distro out there, which would be insane to keep up with -- or limit it to only a few key distributions of Linux, which would limit its accessibility for some users.

**Comment by knotheu** [comment]
32-bit is on it's way out, a lot of linux distro's are not installing it, and I believe Windows is going to be do away with it also, of course I don't know if windows even has a 32-bit system, both my MacBook Pro and Dell are 64-bit, the mac being a hybrid I can do 64-bit but only with dos no efi.
    On Sunday, July 1, 2018, 4:13:08 PM PDT, Donna Whisnant <notifications@github.com> wrote:  
 
 
Glad you got it working. And yes, as I mentioned earlier in this thread, alien is required. That's the program that converts RPM packages to DEB packages. Debian is sort of weird with the whole LSB concept. While Debian itself is probably one of the most LSB compliant distros, due to their strict requirements they actually don't claim to be LSB compliant.

Normally, just installing lsb on most distros gets you all of the core pieces you need, like lsb-core, lsb-release, and alien, etc. That used to be the case with Debian. But it seems that since they don't consider themselves "LSB compliant", they've split up the LSB packages -- unfortunately that makes it more difficult for the average user to get things installed.

Thanks for working through this and letting me know about it. I will see about updating the text on my http://www.purebiblesearch.com/ website to include some details about this to help others out.

If you are wondering why KJPBS uses LSB in the first place, it's so that I can have two installers (one 32-bit and one 64-bit) that will work on nearly all distributions of Linux.  Otherwise, I'd have to develop and maintain system packages for every Linux distro out there, which would be insane to keep up with -- or limit it to only a few key distributions of Linux, which would limit its accessibility for some users.

**Comment by dewhisna** [comment]
Actually, 32 vs 64 bit isn't the primary issue -- it's the number of completely different Linux distros.  Without LSB, I'd have to orchestrate system packages for every major Linux distro like RedHat, Fedora, Mandrake, Suse, Ubuntu, Debian, Mint, Arch, Slax, etc, etc.  The list goes on and on.  Here, this Wikipedia article shows better what I mean:
https://en.wikipedia.org/wiki/List_of_Linux_distributions

And, packages would have to be created for every major release version of each of those distros.  That or only release KJPBS for a few of the major ones and tell everyone else to build it from the source code; they are on their own.  In fact, if you hadn't gotten LSB to work on your system, the next step was for me to tell you how to compile it from the source code manually, which currently isn't trivial to do.

As for 32 vs 64 bit, you can actually enable mixed-architecture in your package manager and install 32 bit apps on a 64 bit side-by-side even.  Most apps forced to be 64-bit apps are just wasting system resources, as every pointer size is now doubled, even if they don't need the extra memory.  But like I said, 32 vs 64 isn't the issue here -- it's the number of distributions with different combinations of common shared libraries and runtimes.  Every different distribution of Linux can be somewhat considered a completely different operating system.

**Comment by dewhisna** [comment]
You probably don't like Ubuntu because of the stupid Unity desktop, which I can't stand either.  Ubuntu itself really isn't much different from Debian.  I used to swear by Kubuntu, which is Ubuntu with the KDE desktop.  Up through 14.04 it was awesome, but they absolutely destroyed it at the 16.04 release.  So I have since switched to Xubuntu, which is the Xfce desktop.  Though I hear that on the last release, Ubuntu has finally switched back to Gnome.  The good thing with Linux is that you can install multiple different desktop environments and switch between them without redoing the whole distro installation.

You could probably compile KJPBS to run on Solus -- though I would be curious if you are trying it again to know if the "Portable Drive Image" version of KJPBS (about halfway down the page at http://www.purebiblesearch.com/) works as-is on Solus.  Those images are essentially zip files of KJPBS without the installer wrapper.  It's designed for people to run KJPBS in a "stealth" manner and not leave footprints on the computer.  You just unzip it and run it.  The big difference is that it doesn't put anything in the system package lists for it, nor install any launch icon for the application menus, nor associate any filetypes with KJPBS.

But, you may be able to run that version on systems without explicitly installing LSB.  By KJPBS being compiled with LSB libraries and mostly statically, it will probably run without LSB itself being installed -- LSB is mainly needed for the installer side of things to register itself with the system package manager, etc.

So if you get a chance when you are experimenting with other Linux distros, try out the Portable Drive Image version too. And even if you were to have to compile KJPBS from source, that doesn't require any programming to do -- just entering lots of commands from the command-line and installing all of the necessary tools and dependencies.

**Comment by knotheu** [comment]
I think compiling KJPBS in Solus would be fun to do if I can download the necessary tools and dependencies. Solus is a disto unlike debian, arch or fedora, but I do like it if I can get the KJPBS either from the usb or compiling it. Can you, in your spare time (lol), send me how to compile KJPBS?Dave 
    On Monday, July 2, 2018, 7:43:01 PM PDT, Donna Whisnant <notifications@github.com> wrote:  
 
 
You probably don't like Ubuntu because of the stupid Unity desktop, which I can't stand either. Ubuntu itself really isn't much different from Debian. I used to swear by Kubuntu, which is Ubuntu with the KDE desktop. Up through 14.04 it was awesome, but they absolutely destroyed it at the 16.04 release. So I have since switched to Xubuntu, which is the Xfce desktop. Though I hear that on the last release, Ubuntu has finally switched back to Gnome. The good thing with Linux is that you can install multiple different desktop environments and switch between them without redoing the whole distro installation.

You could probably compile KJPBS to run on Solus -- though I would be curious if you are trying it again to know if the "Portable Drive Image" version of KJPBS (about halfway down the page at http://www.purebiblesearch.com/) works as-is on Solus. Those images are essentially zip files of KJPBS without the installer wrapper. It's designed for people to run KJPBS in a "stealth" manner and not leave footprints on the computer. You just unzip it and run it. The big difference is that it doesn't put anything in the system package lists for it, nor install any launch icon for the application menus, nor associate any filetypes with KJPBS.

But, you may be able to run that version on systems without explicitly installing LSB. By KJPBS being compiled with LSB libraries and mostly statically, it will probably run without LSB itself being installed -- LSB is mainly needed for the installer side of things to register itself with the system package manager, etc.

So if you get a chance when you are experimenting with other Linux distros, try out the Portable Drive Image version too. And even if you were to have to compile KJPBS from source, that doesn't require any programming to do -- just entering lots of commands from the command-line and installing all of the necessary tools and dependencies.

**Comment by dewhisna** [comment]
Sure, though it shouldn't be posted as part of this thread -- don't know if you realize it or not, but every email you replied to on this thread was automatically posted publicly on GitHub under the issue you had filed.

I don't have your direct email address, as GitHub automatically obfuscated it and similarly you probably don't have mine.  My website URL is posted both here on GitHub and it's listed in the "License" details (clicking the "License" button) on the 'about' screen of KJPBS.  If you go to my personal website, there are details there on how to contact me directly.

Contact me there with an email so that I'll have your email address, then I can reply directly to you with details on how to compile KJPBS -- not that those details shouldn't be publicly available, but it shouldn't be on this thread, and it will be better for me to publish them to the world later in a more coherent fashion.
