### ISSUE TITLE
Request: PKGBUILD for Arch

### ISSUE THREAD

**Issue by deekosta** [dewhisna/KingJamesPureBibleSearch#5]
Hi Donna, thanks for your continued work on this, it is a blessing! I recently migrated to Arch Linux and am having a bit of a time trying to compile this for myself. 

I'm not sure how much work it would be for you, but if it isn't too bad, could you make this available via the Arch AUR? If I can figure the build out myself I may post it there myself. 

Thank you,
Derek

**Comment by dewhisna** [comment]
Unfortunately, I don't know much about Arch Linux or AUR packages.  However, KJPBS is built as a static-link LSB compliant executable and the installer is nothing but a self-extracting wrapper around it.  You can run the KJPBS installer with command line options.  `--help` lists usage details.  And you can pass `--noexec --target NewDir` options to not execute the installation script and to extract the content to a specific `NewDir` folder of your choice.  There's also options like `--list` to list content.  And even a `--tar` option to pass options for extracting specific pieces (as the self-extracting wrapper just uses `tar`).

That will give you the content out of the KJPBS installation executable and then you can locate and run the `rpm2cpio` utility for your system to extract the content of the LSB RPM file of KJPBS that's in that bundle.  Unlike full RedHat/Fedora/CentOS style RPM files, the LSB RPM files are mostly just a fancy zip file.  It does have the RPM prologue details, but that's about it, as it's designed to be distro-independent.

If you use `rpm2cpio` to manually extract the content of the RPM to a folder, you should be able to run KJPBS from the extracted copy.  The core of the KJPBS installer on Linux mainly just uses `alien` to convert the RPM to a native package so that it appears in the system package manager for easy removal, and it creates a system desktop icon and "shortcut" for launching it from the "applications menu", and it registers the `kjs` search file extension, and that's about it.  You could just as well copy the manually extracted content somewhere (usually the `/opt` folder is the preferred systemwide location), add a shortcut to your "applications menu" for your desktop, and run it.

OR, if you don't want to muck around with the self-extracting installation wrapper of KJPBS, you can just download the "Portable Drive Image" zip-file for Linux from the [http://www.purebiblesearch.com/](http://www.purebiblesearch.com/) website, extract that zip file, and run it.  Since that doesn't have the RPM bundling for converting to a native system package with `alien`, then it requires less "LSB dependencies".

But, if you really want to actually compile it yourself, you certainly can.  That won't be as portable, but would work for you to run it.  You can either follow the basic step-by-step process that's in either the `.travis.yml` file or the `docker/docker_build_KJPBS.sh` script, as those capture all of the build dependencies to guide you through how to compile KJPBS from source.

Or, if you install Docker, you should be able to just provision a Docker container and run the KJPBS GUI right out of the Docker Container. Just follow the `README` file in the `docker` folder.

So, if my count is correct, that's at least four different ways you should be able to run KJPBS on Arch Linux:
1) Manually extract the self-extracting KJPBS executable and run it (without compiling anything)
2) Use the Portable Drive Image of KJPBS for Linux (without compiling anything)
3) Let Docker/Packer do the compilation for you and run KJPBS in a Docker Container
4) Use either the `.travis.yml` or `docker/docker_build_KJPBS.sh` script as a guide to do the entire KJPBS source compilation yourself

If you do want to do a write-up on how to run KJPBS on Arch, the best place to post that is probably on the [Discussion Wiki on SourceForge](https://sourceforge.net/p/purebiblesearch/discussion/general/).  There's already a "how-to" there that someone did for Manjaro Linux.  And all of these "how-to" docs should probably be in the same location to make it easier for people to find.
